package com.sanlux.trade.impl.settle.dao;

import com.google.common.collect.ImmutableMap;
import com.sanlux.trade.settle.model.VegaSellerTradeDailySummary;
import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.common.utils.Arguments;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.Map;

/**
 * Code generated by CodeGen
 * Desc: 三力士商家日汇总Dao类
 * Date: 2016-12-15
 */
@Repository
public class VegaSellerTradeDailySummaryDao extends MyBatisDao<VegaSellerTradeDailySummary> {

    public VegaSellerTradeDailySummary findBySellerIdAndSumAtAndSummaryType(Long sellerId, Date sumAt, Integer summaryType){
        return getSqlSession().selectOne(
                sqlId("findBySellerIdAndSumAtAndSummaryType"),
                ImmutableMap.of(
                        "sellerId", sellerId,
                        "sumAt", sumAt,
                        "summaryType", summaryType
                )
        );
    }

    public Boolean createOrderUpdate(VegaSellerTradeDailySummary summary){
        VegaSellerTradeDailySummary exist = findBySellerIdAndSumAtAndSummaryType(summary.getSellerId(),summary.getSumAt(),summary.getSummaryType());
        if(Arguments.notNull(exist)) {
            summary.setId(exist.getId());
            return this.update(summary);
        }else {
            return this.create(summary);
        }
    }
    /**
     * 获取一级(二级)经销商待打款数量
     */
    public Long countDealerPayment (Integer summaryType,Integer transStatus) {
        return getSqlSession().selectOne(sqlId("count"),
                ImmutableMap.of("summaryType",summaryType,"transStatus",transStatus));
    }

}
