package com.sanlux.user.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 公告通知表Model类
 * Date: 2016-11-07
 */
@Data
public class NotifyArticle implements Serializable {
    //TODO: Do not forget add "serialVersionUID" field AND change package path!

    private Long id;
    
    /**
     * 主题
     */
    private String theme;
    
    /**
     * 内容
     */
    private String content;
    
    /**
     * 状态,1:正常，-1：删除,前端不用处理这个字段
     */
    private Integer status;
    
    /**
     * 附件地址
     */
    private String fileUrl;
    
    /**
     * 是否通知供应商，0：不通知，1：通知
     */
    private Integer notifySupplier;
    
    /**
     * 是否通知一级经销商，0：不通知，1：通知
     */
    private Integer notifyDealerFirst;
    
    /**
     * 是否通知二级经销商，0：不通知，1：通知
     */
    private Integer notifyDealerSecond;
    
    /**
     * 额外信息
     */
    private String extraJson;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 更新时间
     */
    private Date updatedAt;
}
