package com.sanlux.user.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 等级表，5个等级Model类
 * Date: 2016-08-03
 */
@Data
public class Rank implements Serializable {

    private static final long serialVersionUID = 1722927227806985127L;
    private Long id;

    private Long pid;
    
    /**
     * 等级名称
     */
    private String name;
    
    /**
     * 成长值起始值
     */
   // private Long integrationStart;
    private Long growthValueStart;
    /**
     * 成长值终止值
     */
    //private Long integrationEnd;
    private Long growthValueEnd;
    /**
     * 折扣值
     */
    private Integer discount;
    
    /**
     * 额外的扩展字段JSON格式
     */
    private String extraJson;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 最后一次更新时间
     */
    private Date updatedAt;
}
