package com.sanlux.user.model;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.common.base.Strings;
import io.terminus.common.utils.JsonMapper;
import io.terminus.parana.common.constants.JacksonType;
import lombok.Data;

import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;

/**
 * Code generated by terminus code gen
 * Desc: 经销商专属会员信息扩展表Model类
 * Date: 2017-09-01
 */
@Data
public class ShopUserExtras implements Serializable {
    private static final long serialVersionUID = -8303432898061461536L;
    private static final ObjectMapper objectMapper = JsonMapper.nonEmptyMapper().getMapper();

    private Long id;

    /**
     * 用户ID
     */
    private Long userId;

    /**
     * 用户手机号
     *
     */
    private String mobile;

    /**
     * 用户名称
     */
    private String userName;
    
    /**
     * 经销商ID
     */
    private Long shopId;
    
    /**
     * 经销商名称
     */
    private String shopName;

    /**
     * 用户类型
     */
    private Integer userType;

    /**
     * 用户状态
     */
    private Integer userStatus;

    /**
     * 公司名称
     */
    private String companyName;

    /**
     * 联系人名称
     */
    private String contactName;

    /**
     * 联系人电话
     */
    private String contactPhone;

    /**
     * 联系人邮件
     */
    private String contactEmail;

    /**
     * 省ID
     */
    private Long provinceId;

    /**
     * 省名称
     */
    private String province;

    /**
     * 城市ID
     */
    private Long cityId;

    /**
     * 城市名称
     */
    private String city;

    /**
     * 县区ID
     */
    private Long regionId;

    /**
     * 县区名称
     */
    private String region;

    /**
     * 街道名称
     */
    private String street;

    /**
     * 邮编
     */
    private String postcode;

    
    /**
     * 扩展字段JSON格式
     */
    private String extraJson;

    /**
     * 扩展字段map格式
     */
    private Map<String, String> extra;

    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 最后一次更新时间
     */
    private Date updatedAt;

    public void setExtraJson(String extraJson) throws Exception {
        this.extraJson = extraJson;
        if(Strings.isNullOrEmpty(extraJson)) {
            this.extra = Collections.emptyMap();
        } else {
            this.extra = objectMapper.readValue(extraJson, JacksonType.MAP_OF_STRING);
        }

    }

    public void setExtra(Map<String, String> extra) {
        this.extra = extra;
        if(extra != null && !extra.isEmpty()) {
            try {
                this.extraJson = objectMapper.writeValueAsString(extra);
            } catch (Exception var3) {
            }
        } else {
            this.extraJson = null;
        }

    }

}
