package com.sanlux.item.impl.service;

import com.google.common.base.Throwables;
import com.sanlux.item.dto.IntegrationItemCriteria;
import com.sanlux.item.impl.dao.IntegrationItemDao;
import com.sanlux.item.model.IntegrationItem;
import com.sanlux.item.service.IntegrationItemReadService;
import io.terminus.boot.rpc.common.annotation.RpcProvider;
import io.terminus.common.model.Paging;
import io.terminus.common.model.Response;
import io.terminus.parana.common.model.PagingCriteria;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 积分商品表读服务实现类
 * Date: 2016-11-07
 */
@Slf4j
@Service
@RpcProvider
public class IntegrationItemReadServiceImpl implements IntegrationItemReadService {

    private final IntegrationItemDao integrationItemDao;

    @Autowired
    public IntegrationItemReadServiceImpl(IntegrationItemDao integrationItemDao) {
        this.integrationItemDao = integrationItemDao;
    }

    @Override
    public Response<IntegrationItem> findById(Long id) {
        try {
            return Response.ok(integrationItemDao.findById(id));
        } catch (Exception e) {
            log.error("find integrationItem by id :{} failed,  cause:{}", id, Throwables.getStackTraceAsString(e));
            return Response.fail("integration.item.find.fail");
        }
    }

    @Override
    public Response<Paging<IntegrationItem>> paging (IntegrationItemCriteria pagingCriteria) {
        try {
            return Response.ok(integrationItemDao.paging(pagingCriteria.toMap()));
        } catch (Exception e) {
            log.error("paging integrationItem by pagingCriteria :{} failed,  cause:{}",
                    pagingCriteria, Throwables.getStackTraceAsString(e));
            return Response.fail("integration.item.paging.fail");
        }
    }
}
