package com.sanlux.user.dto;

import lombok.Data;

import java.io.Serializable;

/**
 * Code generated by terminus code gen
 * Desc: 用户等级表Model类
 * Date: 2016-08-03
 */
@Data
public class UserRank implements Serializable {

    private static final long serialVersionUID = -8891944780018561319L;

    /**
     * 用户ID
     */
    private Long userId;

    /**
     * 用户名称
     */
    private String userName;

    /**
     * 用户当前成长值
     */
    //private Long integration;
    private Long growthValue;
    /**
     * 用户所属等级ID
     */
    private Long rankId;
    /**
     * 用户所属等级名称
     */
    private String rankName;

    /**
     * 头像地址
     */
    private String avatar;

    /**
     * 用户积分
     */
    private Long integration;

}
