package com.sanlux.trade.impl.service;

import com.google.common.base.Throwables;
import com.sanlux.trade.dto.IntegrationOrderCriteria;
import com.sanlux.trade.impl.dao.IntegrationOrderDao;
import com.sanlux.trade.model.IntegrationOrder;
import com.sanlux.trade.service.IntegrationOrderReadService;
import io.terminus.boot.rpc.common.annotation.RpcProvider;
import io.terminus.common.model.Paging;
import io.terminus.common.model.Response;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 积分商品订单读服务实现类
 * Date: 2016-11-07
 */
@Slf4j
@Service
@RpcProvider
public class IntegrationOrderReadServiceImpl implements IntegrationOrderReadService {

    private final IntegrationOrderDao integrationOrderDao;

    @Autowired
    public IntegrationOrderReadServiceImpl(IntegrationOrderDao integrationOrderDao) {
        this.integrationOrderDao = integrationOrderDao;
    }

    @Override
    public Response<IntegrationOrder> findById(Long id) {
        try {
            return Response.ok(integrationOrderDao.findById(id));
        } catch (Exception e) {
            log.error("find integrationOrder by id :{} failed,  cause:{}", id, Throwables.getStackTraceAsString(e));
            return Response.fail("integration.order.find.fail");
        }
    }

    @Override
    public Response<Paging<IntegrationOrder>> paging (IntegrationOrderCriteria criteria) {
        try {
            return Response.ok(integrationOrderDao.paging(criteria.toMap()));
        } catch (Exception e) {
            log.error("paging integration order fail, criteria:{}, cause:{}",
                    criteria, Throwables.getStackTraceAsString(e));
            return Response.fail("integration.order.paging.fail");
        }
    }
}
