package com.sanlux.item.impl.dao;

import com.google.common.collect.ImmutableMap;
import com.sanlux.item.model.IntegrationItem;
import io.terminus.common.mysql.dao.MyBatisDao;
import org.springframework.stereotype.Repository;

/**
 * Code generated by terminus code gen
 * Desc: 积分商品表Dao类
 * Date: 2016-11-07
 */
@Repository
public class IntegrationItemDao extends MyBatisDao<IntegrationItem> {

    public Boolean updateStatus (Long id, Integer status) {
        return getSqlSession().update(sqlId("updateStatus"),
                ImmutableMap.of("id", id, "status", status)) > 0;
    }

    public Boolean updateStockQuantity(Long id, Integer stockQuantity, Integer status) {
        return getSqlSession().update(sqlId("updateStockQuantity"),
                ImmutableMap.of("id", id, "stockQuantity", stockQuantity, "status", status)) > 0;
    }
}
