package com.sanlux.item.impl.dao;

import com.sanlux.item.model.ItemImport;
import io.terminus.common.mysql.dao.MyBatisDao;
import org.springframework.stereotype.Repository;

/**
 * Code generated by terminus code gen
 * Desc: 商品导入处理表Dao类
 * Date: 2016-10-17
 */
@Repository
public class ItemImportDao extends MyBatisDao<ItemImport> {

}
