package com.sanlux.trade.impl.dao;

import com.sanlux.trade.model.IntegrationOrder;
import io.terminus.common.mysql.dao.MyBatisDao;
import org.springframework.stereotype.Repository;

/**
 * Code generated by terminus code gen
 * Desc: 积分商品订单Dao类
 * Date: 2016-11-07
 */
@Repository
public class IntegrationOrderDao extends MyBatisDao<IntegrationOrder> {

    public Boolean delivery(IntegrationOrder integrationOrder) {
        return getSqlSession().update(sqlId("delivery"), integrationOrder) > 0;
    }
}
