package com.sanlux.shop.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 还款履历表Model类
 * Date: 2016-08-29
 */
@Data
public class CreditRepaymentResume implements Serializable {

    private static final long serialVersionUID = -5678187560721707499L;

    private Long id;
    
    /**
     * 操作履历id
     */
    private Long alterResumeId;
    
    /**
     * 本次实际还款(退款)金额
     */
    private Long fee;

    /**
     * 上一次欠款金额
     */
    private Long lastDebtAmount;

    /**
     * 剩余未还款金额
     */
    private Long remainAmount;

    /**
     * 罚息
     */
    private Long fineAmount;

    /**
     * 超出还款金额
     */
    private Long beyondAmount;

    /**
     * 还款类型, (退款、还款)
     */
    private Integer type;
    
    /**
     * 还款状态(0:待运营审核，1:运营审核通过，-1:运营拒绝)运营拒绝后可继续申请运营审核
     */
    private Integer status;
    
    /**
     * 扩展信息字段
     */
    private String extraJson;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 更新时间
     */
    private Date updatedAt;
}
