package com.sanlux.shop.model;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.common.base.Strings;
import io.terminus.common.utils.JsonMapper;
import io.terminus.parana.common.constants.JacksonType;
import lombok.Data;

import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;

/**
 * Code generated by terminus code gen
 * Desc: 三力士 shop extra 表Model类
 * Date: 2016-08-17
 */
@Data
public class VegaShopExtra implements Serializable {

    private static final long serialVersionUID = -1328396244042371467L;

    private static final ObjectMapper objectMapper = JsonMapper.nonEmptyMapper().getMapper();

    private Long id;
    
    /**
     * 店铺ID
     */
    private Long shopId;
    
    /**
     * 上级店铺ID
     */
    private Long shopPid;

    /**
     * 上级店铺(经销商)名称
     */
    private String shopParentName;

    /**
     * 店铺名称
     */
    private String shopName;

    /**
     * 店铺状态
     */
    private Integer shopStatus;
    
    /**
     * 店铺类型
     */
    private Integer shopType;

    /**
     * 店铺授权标志
     */
    private Integer shopAuthorize;

    /**
     * 是否三力士新老会员标记
     */
    private Integer isOldMember;

    /**
     * 用户ID
     */
    private Long userId;

    /**
     * 用户名
     */
    private String userName;
    
    /**
     * 二级经销商的采购折扣
     */
    private Integer purchaseDiscount;

    /**
     * 倍率下限
     */
    private Integer discountLowerLimit;
    
    /**
     * 默认会员折扣, JSON
     */
    private String memberDiscountJson;

    /**
     * 默认会员折扣
     */
    private Map<String, Integer> memberDiscount;
    
    /**
     * 信用额度(可用于支付)
     */
    private Long totalCredit;

    /**
     * 可用信用额度
     */
    private Long availableCredit;

    /**
     * 账龄(还款日期)
     */
    private Integer creditPaymentDays;

    /**
     * 信用额度是否可用, true 可用, false 不可用
     */
    private Boolean isCreditAvailable;

    /**
     * 银行账号
     */
    private String bankAccount;

    /**
     * 联系人姓名
     */
    private String contactName;

    /**
     * 联系电话
     */
    private String contactPhone;

    /**
     * 省市区ID, 名称, 邮编
     */
    private Long provinceId;

    private String province;

    private Long cityId;

    private String city;

    private Long regionId;

    private String region;

    private String street;

    private String postcode;

    private Date createdAt;
    
    private Date updatedAt;

    public void setMemberDiscountJson(String memberDiscountJson) throws Exception{
        this.memberDiscountJson = memberDiscountJson;
        if(Strings.isNullOrEmpty(memberDiscountJson)){
            this.memberDiscount= Collections.emptyMap();
        } else{
            this.memberDiscount = objectMapper.readValue(memberDiscountJson, JacksonType.MAP_OF_INTEGER);
        }
    }

    public void setMemberDiscount(Map<String, Integer> memberDiscount) {
        this.memberDiscount = memberDiscount;
        if(memberDiscount ==null ||memberDiscount.isEmpty()){
            this.memberDiscountJson = null;
        }else{
            try {
                this.memberDiscountJson = objectMapper.writeValueAsString(memberDiscount);
            } catch (Exception e) {
                //ignore this exception
            }
        }
    }

}
