package com.sanlux.trade.settle.model;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.common.base.Strings;
import io.terminus.common.utils.JsonMapper;
import io.terminus.parana.common.constants.JacksonType;
import lombok.Data;

import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;

/**
 * Code generated by CodeGen
 * Desc: 三力士商家日汇总Model类
 * Date: 2016-12-15
 */
@Data
public class VegaSellerTradeDailySummary implements Serializable {

    private static final long serialVersionUID = -4621923444367051657L;

    private static final ObjectMapper objectMapper = JsonMapper.nonEmptyMapper().getMapper();

    private Long id;
    
    /**
     * 商家ID
     */
    private Long sellerId;
    
    /**
     * 商家类型
     */
    private Long sellerType;
    
    /**
     * 商家名称
     */
    private String sellerName;
    
    /**
     * 订单数
     */
    private Integer orderCount;
    
    /**
     * 退款单数
     */
    private Integer refundOrderCount;
    
    /**
     * 应收货款
     */
    private Long originFee;
    
    /**
     * 退款金额
     */
    private Long refundFee;
    
    /**
     * 商家优惠
     */
    private Long sellerDiscount;
    
    /**
     * 电商平台优惠
     */
    private Long platformDiscount;
    
    /**
     * 运费
     */
    private Long shipFee;
    
    /**
     * 运费优惠
     */
    private Long shipFeeDiscount;
    
    /**
     * 实收货款
     */
    private Long actualPayFee;
    
    /**
     * 支付平台佣金
     */
    private Long gatewayCommission;
    
    /**
     * 电商平台佣金
     */
    private Long platformCommission;
    
    /**
     * 商家应收
     */
    private Long sellerReceivableFee;
    
    /**
     * 汇总类型: 0-所有, 1-正向, 2-逆向
     */
    private Integer summaryType;
    
    /**
     * 汇总时间（该数据是某一天的）
     */
    private Date sumAt;
    
    /**
     * 附加字段
     */
    private String extraJson;
    
    /**
     * 差价
     */
    private Long diffFee;
    
    /**
     * 附加佣金1
     */
    private Long commission1;
    
    /**
     * 附加佣金2
     */
    private Long commission2;
    
    /**
     * 附加佣金3
     */
    private Long commission3;
    
    /**
     * 附加佣金4
     */
    private Long commission4;
    
    /**
     * 附加佣金5
     */
    private Long commission5;
    
    /**
     * 打款状态
     */
    private Integer transStatus;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 最新更新时间
     */
    private Date updatedAt;

    private Map<String, String> extra;

    public void setExtraJson(String extraJson) throws Exception{
        this.extraJson = extraJson;
        if(Strings.isNullOrEmpty(extraJson)){
            this.extra= Collections.emptyMap();
        } else{
            this.extra = objectMapper.readValue(extraJson, JacksonType.MAP_OF_STRING);
        }
    }

    public void setExtra(Map<String, String> extra) {
        this.extra = extra;
        if(extra ==null ||extra.isEmpty()){
            this.extraJson = null;
        }else{
            try {
                this.extraJson = objectMapper.writeValueAsString(extra);
            } catch (Exception e) {
                //ignore this exception
            }
        }
    }
}
