package com.sanlux.category.service;

import com.google.common.base.Optional;
import com.sanlux.category.model.CategoryAuthe;
import io.terminus.common.model.Response;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 经销商授权类目读服务
 * Date: 2016-08-04
 */

public interface CategoryAutheReadService {

    /**
     * 根据id查询经销商授权类目
     * @param categoryAutheId 主键id
     * @return 经销商授权类目
     */
    Response<Optional<CategoryAuthe>> findCategoryAutheById(Long categoryAutheId);

    /**
     * 根据经销商店铺ID查找授权类目
     * @param shopId 店铺ID
     * @return 授权类目表
     */
    Response<Optional<CategoryAuthe>> findCategoryAutheByShopId (Long shopId);

    /**
     * 根据经销商IDs批量查询授权类目
     * @param shopIds shopIds
     * @return List
     */
    Response<List<CategoryAuthe>> findByShopIds (List<Long> shopIds);

}
