package com.sanlux.category.service;

import com.sanlux.category.dto.VegaCategoryDiscountDto;
import com.sanlux.category.model.CategoryAuthe;
import io.terminus.common.model.Response;

/**
 * Code generated by terminus code gen
 * Desc: 经销商授权类目写服务
 * Date: 2016-08-04
 */

public interface CategoryAutheWriteService {

    /**
     * 创建CategoryAuthe
     * @param categoryAuthe 授权类目表
     * @return 主键id
     */
    Response<Long> createOrUpdateCategoryAuthe(CategoryAuthe categoryAuthe);

    /**
     * 更新授权类目表类目折扣
     * @param shopId 经销商店铺ID
     * @param vegaCategoryDiscountDto 类目折扣DTO
     * @return 成功与否
     */
    Response<Boolean> updateCategoryDiscount(Long shopId, VegaCategoryDiscountDto vegaCategoryDiscountDto);

    /**
     * 更新CategoryAuthe
     * @param categoryAuthe 授权类目表
     * @return 是否成功
     */
    Response<Boolean> updateCategoryAuthe(CategoryAuthe categoryAuthe);

    /**
     * 根据主键id删除CategoryAuthe
     * @param categoryAutheId 授权类目表ID
     * @return 是否成功
     */
    Response<Boolean> deleteCategoryAutheById(Long categoryAutheId);
}