package com.sanlux.trade.settle.service;

import com.sanlux.trade.settle.model.AllinpayTrans;
import io.terminus.common.model.Response;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 读服务
 * Date: 2016-10-20
 */

public interface AllinpayTransReadService {

    /**
     * 根据id查询
     * @param Id 主键id
     * @return 
     */
    Response<AllinpayTrans> findById(Long Id);
}
