package com.sanlux.trade.impl.settle.service;

import com.google.common.base.Throwables;
import com.sanlux.trade.impl.settle.dao.AllinpayTransDao;
import com.sanlux.trade.settle.model.AllinpayTrans;
import com.sanlux.trade.settle.service.AllinpayTransReadService;
import io.terminus.boot.rpc.common.annotation.RpcProvider;
import io.terminus.common.model.Response;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Code generated by terminus code gen
 * Desc: 读服务实现类
 * Date: 2016-10-20
 */
@Slf4j
@Service
@RpcProvider
public class AllinpayTransReadServiceImpl implements AllinpayTransReadService {

    private final AllinpayTransDao allinpayTransDao;

    @Autowired
    public AllinpayTransReadServiceImpl(AllinpayTransDao allinpayTransDao) {
        this.allinpayTransDao = allinpayTransDao;
    }

    @Override
    public Response<AllinpayTrans> findById(Long Id) {
        try {
            return Response.ok(allinpayTransDao.findById(Id));
        } catch (Exception e) {
            log.error("find allinpayTrans by id :{} failed,  cause:{}", Id, Throwables.getStackTraceAsString(e));
            return Response.fail("allinpay.trans.find.fail");
        }
    }
}
