package com.sanlux.item.model;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.common.base.Strings;
import io.terminus.common.utils.JsonMapper;
import io.terminus.parana.common.constants.JacksonType;
import lombok.Data;

import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;

/**
 * Code generated by terminus code gen
 * Desc: 积分商品表Model类
 * Date: 2016-11-07
 */
@Data
public class IntegrationItem implements Serializable {


    private static final long serialVersionUID = -1121844514553858090L;

    private static final ObjectMapper objectMapper = JsonMapper.nonEmptyMapper().getMapper();


    private Long id;
    
    /**
     * 积分商品名称
     */
    private String name;
    
    /**
     * 库存
     */
    private Integer stockQuantity;
    
    /**
     * 积分商品状态,1:上架, -1:下架, -3:删除
     */
    private Integer status;
    
    /**
     * 积分售价
     */
    private Integer integrationPrice;
    
    /**
     * 积分商品图片
     */
    private String imagesJson;

    /**
     * 扩展信息,不存数据库
     */
    private Map<String, String> extra;

    /**
     * 扩展信息字段,存数据库
     */
    private String extraJson;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 更新时间
     */
    private Date updatedAt;

    public void setExtraJson(String extraJson) throws Exception{
        this.extraJson = extraJson;
        if(Strings.isNullOrEmpty(extraJson)){
            this.extra= Collections.emptyMap();
        } else{
            this.extra = objectMapper.readValue(extraJson, JacksonType.MAP_OF_STRING);
        }
    }

    public void setExtra(Map<String, String> extra) {
        this.extra = extra;
        if(extra ==null ||extra.isEmpty()){
            this.extraJson = null;
        }else{
            try {
                this.extraJson = objectMapper.writeValueAsString(extra);
            } catch (Exception e) {
                //ignore this exception
            }
        }
    }
}
