package com.sanlux.item.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 商品导入处理表Model类
 * Date: 2016-10-17
 */
@Data
public class ItemImport implements Serializable {

    private static final long serialVersionUID = 4943043386795140466L;

    private Long id;
    
    /**
     * 供应商店铺 ID
     */
    private Long shopId;
    
    /**
     * 商品上传数据 {shopId: 1, products: [...]}
     */
    private String itemUploadedJson;
    
    /**
     * 执行状态, 0: 未执行, 1: 成功, -1: 失败
     */
    private Integer status;
    
    /**
     * 失败时的错误原因 (错误报告)
     */
    private String errorResult;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 更新时间
     */
    private Date updatedAt;

    public enum Status {
        /**
         * 未执行
         */
        INIT(0),
        /**
         * 成功
         */
        SUCCESS(1),
        /**
         * 失败
         */
        FAIL(-1),
        ;

        private final int value;

        public final int value() {
            return value;
        }

        Status(int value) {
            this.value = value;
        }
    }
}
