package com.sanlux.trade.service;

import com.google.common.base.Optional;
import com.sanlux.trade.dto.OrderDispatchCriteria;
import com.sanlux.trade.model.OrderDispatchRelation;
import io.terminus.common.model.Paging;
import io.terminus.common.model.Response;

/**
 * Code generated by terminus code gen
 * Desc: 订单派送关联表读服务
 * Date: 2016-08-16
 */

public interface OrderDispatchRelationReadService {

    /**
     * 根据id查询订单派送关联表
     *
     * @param orderDispatchRelationId 主键id
     * @return 订单派送关联表
     */
    Response<Optional<OrderDispatchRelation>> findOrderDispatchRelationById(Long orderDispatchRelationId);


    /**
     * 根据id查询订单派送关联表
     *
     * @param orderId 订单id
     * @param dispatchShopId 订单被派送给某个店铺的店铺id
     * @return 订单派送关联表
     */
    Response<Optional<OrderDispatchRelation>> findByOrderIdAndDispatchShopId(Long orderId,Long dispatchShopId);

    /**
     * 派送单信息分页
     * @return 分页信息
     */
    Response<Paging<OrderDispatchRelation>> paging(OrderDispatchCriteria orderDispatchCriteria);


}
