package com.sanlux.trade.service;

import com.sanlux.trade.model.OrderDispatchRelation;
import io.terminus.common.model.Response;
import io.terminus.parana.common.model.ParanaUser;
import io.terminus.parana.order.model.OrderBase;
import io.terminus.parana.order.model.ShopOrder;
import io.terminus.parana.shop.model.Shop;

/**
 * Code generated by terminus code gen
 * Desc: 订单派送关联表写服务
 * Date: 2016-08-16
 */

public interface OrderDispatchRelationWriteService {

    /**
     * 创建OrderDispatchRelation
     * @param orderDispatchRelation 订单派送关联表
     * @return 主键id
     */
    Response<Long> createOrderDispatchRelation(OrderDispatchRelation orderDispatchRelation);


    /**
     * 派单
     * @param orderBase 待派送订单
     * @param shop 派送给某个店铺
     * @param paranaUser 当前操作人
     * @return 是否派送成功
     */
    Response<Boolean> dispatchOrder(OrderBase orderBase ,Shop shop,ParanaUser paranaUser, Integer newOrderStatus);

    /**
     * 更新OrderDispatchRelation
     * @param orderDispatchRelation 订单派送关联表
     * @return 是否成功
     */
    Response<Boolean> updateOrderDispatchRelation(OrderDispatchRelation orderDispatchRelation);

    /**
     * 根据主键id删除OrderDispatchRelation
     * @param orderDispatchRelationId 订单派送关联表
     * @return 是否成功
     */
    Response<Boolean> deleteOrderDispatchRelationById(Long orderDispatchRelationId);
}