package com.sanlux.user.service;

import com.google.common.base.Optional;
import com.sanlux.user.dto.scope.DeliveryScopeDto;
import com.sanlux.user.model.DeliveryScope;
import io.terminus.common.model.Response;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 供货区域读服务
 * Date: 2016-08-08
 */

public interface DeliveryScopeReadService {

    /**
     * 根据id查询供货区域
     * @param deliveryScopeId 主键id
     * @return 供货区域
     */
    Response<Optional<DeliveryScope>> findDeliveryScopeById(Long deliveryScopeId);

    /**
     * 根据店铺ID获取供货区域List
     * @param shopId 店铺ID
     * @return 供货区域List
     */
    Response<Optional<List<DeliveryScopeDto>>> findByShopId(Long shopId);


    /**
     * 根据店铺ID获取供货区域表
     * @param shopId 店铺ID
     * @return 供货区域表
     */
    Response<Optional<DeliveryScope>> findDeliveryScopeByShopId(Long shopId);


}
