package com.sanlux.user.service;

import com.sanlux.user.model.DeliveryScope;
import io.terminus.common.model.Response;


/**
 * Code generated by terminus code gen
 * Desc: 供货区域写服务
 * Date: 2016-08-08
 */

public interface DeliveryScopeWriteService {

    /**
     * 创建或更新配送范围
     * @param deliveryScope 配送范围表
     * @return 配送范围表ID
     */
    Response<Long> createOrUpdateDeliveryScope(DeliveryScope deliveryScope);

    /**
     * 更新DeliveryScope
     * @param deliveryScope
     * @return 是否成功
     */
    Response<Boolean> updateDeliveryScope(DeliveryScope deliveryScope);

    /**
     * 根据主键id删除DeliveryScope
     * @param deliveryScopeId
     * @return 是否成功
     */
    Response<Boolean> deleteDeliveryScopeById(Long deliveryScopeId);
}