package com.sanlux.user.service;

import com.sanlux.user.dto.criteria.NotifyArticleCriteria;
import com.sanlux.user.model.NotifyArticle;
import io.terminus.common.model.Paging;
import io.terminus.common.model.Response;


/**
 * Code generated by terminus code gen
 * Desc: 公告通知表读服务
 * Date: 2016-11-07
 */

public interface NotifyArticleReadService {

    /**
     * 根据id查询公告通知表
     * @param id 主键id
     * @return 公告通知表
     */
    Response<NotifyArticle> findById(Long id);

    Response<Paging<NotifyArticle>> paging(NotifyArticleCriteria criteria);


}
