package com.sanlux.user.service;

import com.sanlux.user.model.NotifyArticle;
import io.terminus.common.model.Response;

/**
 * Code generated by terminus code gen
 * Desc: 公告通知表写服务
 * Date: 2016-11-07
 */

public interface NotifyArticleWriteService {

    /**
     * 创建NotifyArticle
     * @param notifyArticle
     * @return 主键id
     */
    Response<Long> create(NotifyArticle notifyArticle);

    /**
     * 更新NotifyArticle
     * @param notifyArticle
     * @return 是否成功
     */
    Response<Boolean> update(NotifyArticle notifyArticle);

    /**
     * 根据主键id删除NotifyArticle
     * @param notifyArticleId
     * @return 是否成功
     */
    Response<Boolean> deleteById(Long notifyArticleId);
}