package com.sanlux.user.service;

import com.sanlux.user.model.Rank;
import io.terminus.common.model.Response;

/**
 * Code generated by terminus code gen
 * Desc: 等级表，5个等级写服务
 * Date: 2016-08-03
 */

public interface RankWriteService {

    /**
     * 创建Rank
     * @param rank
     * @return 主键id
     */
    Response<Long> createRank(Rank rank);

    /**
     * 更新Rank
     * @param rank
     * @return 是否成功
     */
    Response<Boolean> updateRank(Rank rank);

    /**
     * 根据主键id删除Rank
     * @param rankId
     * @return 是否成功
     */
    Response<Boolean> deleteRankById(Long rankId);


    Response<Boolean> updateRank(Long id,Long pid,Integer growthValueStart,Integer growthValueEnd,Integer discount);




}