package com.sanlux.user.service;

import com.google.common.base.Optional;
import com.sanlux.user.dto.criteria.RankCriteria;
import com.sanlux.user.model.Rank;
import io.terminus.common.model.Paging;
import io.terminus.common.model.Response;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 等级表，5个等级读服务
 * Date: 2016-08-03
 */

public interface RankReadService {

    /**
     * 根据id查询等级表，5个等级
     * @param rankId 主键id
     * @return 等级表，5个等级
     */
    Response<Optional<Rank>> findRankById(Long rankId);

    /**
     * 根据积分查询积分所属等级表
     * @param integral 积分
     * @return 等级
     */
    Response<Optional<Rank>> findRankByIntegral(Long integral);

    /**
     * 根据条件获取等级分页
     * @param criteria 分页条件
     * @return 等级分页
     */
    Response<Paging<Rank>> paging(RankCriteria criteria);



    Response<List<Rank>> findAll();

}
