package com.sanlux.user.service;

import com.google.common.base.Optional;
import com.sanlux.user.model.UserRankResume;
import io.terminus.common.model.Response;

/**
 * Code generated by terminus code gen
 * Desc: 等级履历表读服务
 * Date: 2016-08-04
 */

public interface UserRankResumeReadService {

    /**
     * 根据id查询等级履历表
     * @param userRankResumeId 主键id
     * @return 等级履历表
     */
    Response<Optional<UserRankResume>> findUserRankResumeById(Long userRankResumeId);
}
