package com.sanlux.user.service;

import com.sanlux.user.model.UserRankResume;
import io.terminus.common.model.Response;

/**
 * Code generated by terminus code gen
 * Desc: 等级履历表写服务
 * Date: 2016-08-04
 */

public interface UserRankResumeWriteService {

    /**
     * 创建UserRankResume
     * @param userRankResume
     * @return 主键id
     */
    Response<Long> createUserRankResume(UserRankResume userRankResume);

    /**
     * 更新UserRankResume
     * @param userRankResume
     * @return 是否成功
     */
    Response<Boolean> updateUserRankResume(UserRankResume userRankResume);

    /**
     * 根据主键id删除UserRankResume
     * @param userRankResumeId
     * @return 是否成功
     */
    Response<Boolean> deleteUserRankResumeById(Long userRankResumeId);




}