package com.sanlux.user.service;

import com.sanlux.user.dto.UserRank;
import io.terminus.common.model.Response;


/**
 * Code generated by terminus code gen
 * Desc: 用户等级表读服务
 * Date: 2016-08-03
 */

public interface UserRankReadService {

    /**
     * 获取用户等级信息
     * @param userId 用户ID
     * @return 用户等级信息
     */
    Response<UserRank> findUserRankByUserId(Long userId);

    /**
     * 获取用户积分
     * @param userId 用户ID
     * @return 用户积分
     */
    Response<Long> findIntegrationByUserId(Long userId);

    /**
     * 根据手机号查找积分
     * @param mobile 手机号
     * @return 积分值
     */
    Response<Long> findIntegrationByMobile(String mobile);


}
