package com.sanlux.user.impl.service;

import com.google.common.base.Optional;
import com.google.common.base.Throwables;
import com.sanlux.user.impl.dao.UserRankResumeDao;
import com.sanlux.user.model.UserRankResume;
import com.sanlux.user.service.UserRankResumeReadService;
import io.terminus.common.model.Response;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Code generated by terminus code gen
 * Desc: 等级履历表读服务实现类
 * Date: 2016-08-04
 */
@Slf4j
@Service
public class UserRankResumeReadServiceImpl implements UserRankResumeReadService {

    private final UserRankResumeDao userRankResumeDao;

    @Autowired
    public UserRankResumeReadServiceImpl(UserRankResumeDao userRankResumeDao) {
        this.userRankResumeDao = userRankResumeDao;
    }


    @Override
    public Response<Optional<UserRankResume>> findUserRankResumeById(Long userRankResumeId) {
        try {
            return Response.ok(Optional.fromNullable(userRankResumeDao.findById(userRankResumeId)));
        } catch (Exception e) {
            log.error("find userRankResume by id failed, userRankResumeId:{}, cause:{}", userRankResumeId, Throwables.getStackTraceAsString(e));
            return Response.fail("user.rank.resume.find.fail");
        }
    }
}
