package com.sanlux.trade.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 订单派送关联表Model类
 * Date: 2016-08-16
 */
@Data
public class OrderDispatchRelation implements Serializable {

    private static final long serialVersionUID = 7598567606182254049L;
    private Long id;
    
    /**
     * 操作人ID
     */
    private Long operateId;
    
    /**
     * 操作人名称
     */
    private String operateName;
    
    /**
     * 订单id
     */
    private Long orderId;
    
    /**
     * 接单店铺id
     */
    private Long receiveShopId;
    
    /**
     * 派单店铺id
     */
    private Long dispatchShopId;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 更新时间
     */
    private Date updatedAt;
}
