package com.sanlux.trade.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: Model类
 * Date: 2016-08-09
 */
@Data
public class PurchaseSkuOrder implements Serializable {

    private static final long serialVersionUID = 147726490821844990L;
    private Long id;
    
    /**
     * 采购单id
     */
    private Long purchaseId;
    
    /**
     * 采购员id
     */
    private Long buyerId;
    
    /**
     * 采购员名称
     */
    private String buyerName;
    
    /**
     * 店铺id
     */
    private Long shopId;

    /**
     * 店铺名称
     */
    private String shopName;


    /**
     * 对应销售属性id
     */
    private Long skuId;
    
    /**
     * 数量
     */
    private Integer quantity;
    
    /**
     * 0未选中，1已选中
     */
    private Integer status;
    
    /**
     * 扩展字段JSON格式
     */
    private String extraJson;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 更新时间
     */
    private Date updatedAt;
}
