package com.sanlux.item.impl.dao;

import com.sanlux.item.BaseDaoTest;
import com.sanlux.item.model.ItemImport;
import io.terminus.common.model.Paging;
import org.junit.Before;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertThat;


/**
 * Code generated by terminus code gen
 * Desc: 商品导入处理表Dao 测试类
 * Date: 2016-10-17
 */
public class ItemImportDaoTest extends BaseDaoTest {



    @Autowired
    private ItemImportDao itemImportDao;

    private ItemImport itemImport;

    @Before
    public void init() {
        itemImport = make();

        itemImportDao.create(itemImport);
        assertNotNull(itemImport.getId());
    }

    @Test
    public void findById() {
        ItemImport itemImportExist = itemImportDao.findById(itemImport.getId());

        assertNotNull(itemImportExist);
    }

    @Test
    public void update() {
        // todo
        itemImport.setUpdatedAt(new Date());
        itemImportDao.update(itemImport);

        ItemImport  updated = itemImportDao.findById(itemImport.getId());
        // todo
        //assertEquals(updated.getHasDisplay(), Boolean.TRUE);
    }

    @Test
    public void delete() {
        itemImportDao.delete(itemImport.getId());

        ItemImport deleted = itemImportDao.findById(itemImport.getId());
        assertNull(deleted);
    }

    @Test
    public void paging() {
        Map<String, Object> params = new HashMap<>();
        //todo
        //params.put("userId", itemImport.getUserId());
        Paging<ItemImport > itemImportPaging = itemImportDao.paging(0, 20, params);

        assertThat(itemImportPaging.getTotal(), is(1L));
        assertEquals(itemImportPaging.getData().get(0).getId(), itemImport.getId());
    }

    private ItemImport make() {
        ItemImport itemImport = new ItemImport();

        
        itemImport.setShopId(1L);
        
        itemImport.setItemUploadedJson(null);
        
        itemImport.setStatus(1);
        
        itemImport.setErrorResult("error");
        
        itemImport.setCreatedAt(new Date());
        
        itemImport.setUpdatedAt(new Date());
        

        return itemImport;
    }

}