package com.sanlux.item.service;

import com.sanlux.item.model.IntegrationItem;
import io.terminus.common.model.Response;

/**
 * Code generated by terminus code gen
 * Desc: 积分商品表写服务
 * Date: 2016-11-07
 */

public interface IntegrationItemWriteService {

    /**
     * 创建IntegrationItem
     * @param integrationItem
     * @return 主键id
     */
    Response<Long> create(IntegrationItem integrationItem);

    /**
     * 更新IntegrationItem
     * @param integrationItem
     * @return 是否成功
     */
    Response<Boolean> update(IntegrationItem integrationItem);

    /**
     * 根据主键id删除IntegrationItem
     * @param integrationItemId
     * @return 是否成功
     */
    Response<Boolean> deleteById(Long integrationItemId);

    /**
     * 更新积分商品状态
     * @param id 积分商品ID
     * @param status 积分商品状态
     * @return Boolean
     */
    Response<Boolean> setStatus(Long id, Integer status);

    /**
     * 检查库存并减库存
     * @param id 商品ID
     * @param quantity 数量
     * @return boolean
     */
    Response<Boolean> checkAndReduceStock(Long id, Integer quantity);
}