package com.sanlux.item.service;

import com.sanlux.item.dto.IntegrationItemCriteria;
import com.sanlux.item.model.IntegrationItem;
import io.terminus.common.model.Paging;
import io.terminus.common.model.Response;
import io.terminus.parana.common.model.PagingCriteria;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 积分商品表读服务
 * Date: 2016-11-07
 */

public interface IntegrationItemReadService {

    /**
     * 根据id查询积分商品表
     * @param id 主键id
     * @return 积分商品表
     */
    Response<IntegrationItem> findById(Long id);

    /**
     * paging
     * @param pagingCriteria 查询条件
     * @return paging
     */
    Response<Paging<IntegrationItem>> paging (IntegrationItemCriteria pagingCriteria);
}
