package com.sanlux.item.service;

import com.sanlux.item.dto.ItemsToCreate;
import com.sanlux.item.dto.api.SubmittedItemImportDto;
import com.sanlux.item.dto.excel.UploadRaw;
import io.terminus.common.model.Response;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 商品导入处理表写服务
 * Date: 2016-10-17
 */

public interface ItemImportWriteService {


    Response<Long> uploadToImportRaw (Long shopId, UploadRaw rawData);

    /**
     * 第三方平台商品批量Excel导入(目前规格是根据土猫网定制)
     * 备注:
     * 1.不导入销售属性(都是单规格商品)
     * 2.不导入非销售属性
     * 3.类目ID通过对方系统类目ID确定
     * 4.导入商品详情(获取土猫网的商品简介图列表)
     * @param shopId   供应商Id
     * @param rawData  导入数据
     * @return 后台导入任务执行Id
     */
    Response<Long> importItemsByExcel (Long shopId, UploadRaw rawData);

    /**
     * 商品批量导入接口
     * @param shopId                    接单店铺
     * @param outIdTag                  外部ID前缀
     * @param deliveryFeeTemplateId     运营模板Id
     * @param submittedItemImportDto    导入封装数据
     * @param type                      导入数据类型(VegaItemImportType),默认为API方式
     * @return 后台导入执行任务Id
     */
    Response<Long> importItemsByApi (Long shopId, String outIdTag, Long deliveryFeeTemplateId, SubmittedItemImportDto submittedItemImportDto, Integer type);

    /**
     * 商品批量修改接口
     * @param shopId                    接单店铺
     * @param outIdTag                  外部ID前缀
     * @param submittedItemImportDto    导入封装数据
     * @return 是否成功
     */
    Response<Boolean> updateItemsByApi (Long shopId, String outIdTag, SubmittedItemImportDto submittedItemImportDto);

    /**
     * 商品批量删除接口
     * @param shopId                   店铺Id
     * @param itemIds                  删除的item
     * @param skuIds                   删除的sku
     * @return 是否成功
     */
    Response<Boolean> deleteItemsByApi (Long shopId, List<Long> itemIds, List<Long> skuIds);


    /**
     * 数据导入
     * @param shopId 店铺Id
     * @param items  导入商品
     * @param type   导入类型  1: 接口导入 0: excel导入
     * @return id
     */
    Response<Long> uploadToImport(Long shopId, List<ItemsToCreate> items, Integer type);

    /**
     * 执行导入
     * @param handlerId 处理 ID
     * @param type      导入类型  1: 接口导入 0: excel导入
     * @return 处理成功
     */
    Response<Boolean> doImportItem(Long handlerId, Integer type);

    /**
     * 批量创建商品
     * @param shopId 店铺ID
     * @param items 商品
     * @param type  导入类型  1: 接口导入 0: excel导入
     * @return Boolean
     */
    Response<Boolean> bulkCreateItem(long shopId, List<ItemsToCreate> items, Integer type);
}