package com.sanlux.shop.service;

import com.sanlux.shop.model.CreditAlterResume;
import com.sanlux.shop.model.CreditRepaymentResume;
import com.sanlux.shop.model.VegaShopExtra;
import io.terminus.common.model.Response;

/**
 * Code generated by terminus code gen
 * Desc: 经销商信用额度变更履历写服务
 * Date: 2016-08-11
 */
public interface CreditAlterResumeWriteService {

    /**
     * 创建额度履历
     * @param resume 履历信息
     * @return ID
     */
    Response<Long> create(CreditAlterResume resume);

    /**
     * 创建履历信息, 同时需要更新店铺信用额度信息
     *
     * @param resume 额度履历信息
     * @param shopExtra 店铺信息, 需要更新最新信用额度
     * @return 主键id
     */
    Response<Boolean> create(CreditAlterResume resume, VegaShopExtra shopExtra);

    /**
     * 更新CreditAlterResume
     * @param creditAlterResume 额度履历信息
     * @return 是否成功
     */
    Response<Boolean> update(CreditAlterResume creditAlterResume);

    /**
     * 根据主键id删除CreditAlterResume
     * @param id 额度履历ID
     * @return 是否成功
     */
    Response<Boolean> delete(Long id);

    /**
     * 根据dealerId删除对应商家所有CreditAlterResume
     * @param shopId 额度履历ID
     * @return 是否成功
     */
    Response<Integer> deleteByShopId(Long shopId);

    /**
     * <p>
     * 添加信用额度消费还款履历
     * </p>
     * @param shopExtra 店铺信息(必须设置 shopId)
     * @param alterResume 信用额度履历
     * @param operatedByAdmin 额度变更履历(类型为运营操作的还款履历信息)
     * @param repaymentResume 还款履历
     * @return 添加结果
     */
    Response<Boolean> createRepaymentResume(VegaShopExtra shopExtra,
                                            CreditAlterResume alterResume,
                                            CreditAlterResume operatedByAdmin,
                                            CreditRepaymentResume repaymentResume);

    /**
     * <p>
     * 添加信用额度消费还款履历(专属会员信用额度支付退款时调用)
     * 专属会员信息由于代码不在同一个模块,暂时在另外一个事务更新
     * </p>
     * @param alterResume 信用额度履历
     * @param operatedByAdmin 额度变更履历(类型为运营操作的还款履历信息)
     * @param repaymentResume 还款履历
     * @return 添加结果
     */
    Response<Boolean> createRepaymentResume(CreditAlterResume alterResume,
                                            CreditAlterResume operatedByAdmin,
                                            CreditRepaymentResume repaymentResume);

}
