package com.sanlux.shop.service;

import com.google.common.base.Optional;
import com.sanlux.shop.dto.CreditRepaymentDetail;
import com.sanlux.shop.model.CreditRepaymentResume;
import io.terminus.common.model.Response;

/**
 * Code generated by terminus code gen
 * Desc: 还款履历表读服务
 * Date: 2016-08-29
 */
public interface CreditRepaymentResumeReadService {

    /**
     * 根据id查询还款履历表
     *
     * @param id id
     * @return 信息
     */
    Response<CreditRepaymentResume> findById(Long id);

    /**
     * 通过额度变更履历ID查询还款履历
     *
     * @param alterResumeId 额度履历ID
     * @return 信息
     */
    Response<CreditRepaymentDetail> findByAlterResumeId(Long alterResumeId);

    /**
     * 拿到上一次的还款履历ID
     *
     * @param alterResumeId 额度履历ID
     * @return 履历信息
     */
    Response<Optional<CreditRepaymentResume>> findLastRepaymentByAlterResumeId(Long alterResumeId);
}
