package com.sanlux.shop.impl.service;

import com.google.common.base.Throwables;
import com.sanlux.shop.impl.dao.CreditRepaymentResumeDao;
import com.sanlux.shop.model.CreditRepaymentResume;
import com.sanlux.shop.service.CreditRepaymentResumeWriteService;
import io.terminus.boot.rpc.common.annotation.RpcProvider;
import io.terminus.common.model.Response;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Code generated by terminus code gen
 * Desc: 还款履历表写服务实现类
 * Date: 2016-08-29
 */
@Slf4j
@Service
@RpcProvider
public class CreditRepaymentResumeWriteServiceImpl implements CreditRepaymentResumeWriteService {

    private final CreditRepaymentResumeDao creditRepaymentResumeDao;

    @Autowired
    public CreditRepaymentResumeWriteServiceImpl(CreditRepaymentResumeDao creditRepaymentResumeDao) {
        this.creditRepaymentResumeDao = creditRepaymentResumeDao;
    }

    @Override
    public Response<Long> create(CreditRepaymentResume creditRepaymentResume) {
        try {
            creditRepaymentResumeDao.create(creditRepaymentResume);
            return Response.ok(creditRepaymentResume.getId());
        } catch (Exception e) {
            log.error("create creditRepaymentResume failed, creditRepaymentResume:{}, cause:{}", creditRepaymentResume, Throwables.getStackTraceAsString(e));
            return Response.fail("credit.repayment.resume.create.fail");
        }
    }

    @Override
    public Response<Boolean> update(CreditRepaymentResume creditRepaymentResume) {
        try {
            return Response.ok(creditRepaymentResumeDao.update(creditRepaymentResume));
        } catch (Exception e) {
            log.error("update creditRepaymentResume failed, creditRepaymentResume:{}, cause:{}", creditRepaymentResume, Throwables.getStackTraceAsString(e));
            return Response.fail("credit.repayment.resume.update.fail");
        }
    }

    @Override
    public Response<Boolean> deleteById(Long id) {
        try {
            return Response.ok(creditRepaymentResumeDao.delete(id));
        } catch (Exception e) {
            log.error("delete creditRepaymentResume failed, creditRepaymentResumeId:{}, cause:{}", id, Throwables.getStackTraceAsString(e));
            return Response.fail("credit.repayment.resume.delete.fail");
        }
    }
}
