package com.sanlux.user.impl.dao;

import com.google.common.base.Optional;
import com.sanlux.user.model.DeliveryScope;
import io.terminus.common.mysql.dao.MyBatisDao;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 供货区域Dao类
 * Date: 2016-08-08
 */
@Repository
public class DeliveryScopeDao extends MyBatisDao<DeliveryScope> {

    /**
     * 根据店铺ID获取供货范围
     * @param shopId 店铺ID
     * @return 供货区域表
     */
    public Optional<DeliveryScope> findDeliveryScopeByShopId(Long shopId) {
        return Optional.fromNullable(
                getSqlSession().<DeliveryScope>selectOne(sqlId("findDeliveryScopeByShopId"), shopId));
    }

    /**
     * 根据店铺ID获取供货范围List
     * @param pId 上级店铺ID
     * @return 供货区域表List
     */
    public Optional<List<DeliveryScope>> findDeliveryScopeByPId(Long pId) {
        return Optional.fromNullable(
                getSqlSession().<DeliveryScope>selectList(sqlId("findDeliveryScopeByPId"), pId));
    }

    /**
     * 根据店铺ID更新供货范围
     * @param deliveryScope 供货区域表
     * @return Boolean
     */
    public Boolean updateScopeByShopId(DeliveryScope deliveryScope) {
        return getSqlSession().update(sqlId("updateScopeByShopId"), deliveryScope) == 1;
    }

    /**
     * 更新供货范围
     * @param deliveryScope 供货区域表
     * @return Boolean
     */
    public Boolean updateScope(DeliveryScope deliveryScope) {
        return getSqlSession().update(sqlId("updateScope"), deliveryScope) == 1;
    }

    /**
     * 获取所有配送了供货范围的店铺ID
     * @return 店铺IDList
     */
    public List<Long> findAllShopIds() {
        return getSqlSession().selectList(sqlId("findAllShopIds"));
    }

}
