package com.sanlux.user.impl.dao;

import com.sanlux.user.model.NotifyArticle;
import io.terminus.common.mysql.dao.MyBatisDao;
import org.springframework.stereotype.Repository;

/**
 * Code generated by terminus code gen
 * Desc: 公告通知表Dao类
 * Date: 2016-11-07
 */
@Repository
public class NotifyArticleDao extends MyBatisDao<NotifyArticle> {

}
