package com.sanlux.user.impl.dao;

import com.sanlux.user.model.UserRankResume;
import io.terminus.common.mysql.dao.MyBatisDao;
import org.springframework.stereotype.Repository;

/**
 * Code generated by terminus code gen
 * Desc: 等级履历表Dao类
 * Date: 2016-08-04
 */
@Repository
public class UserRankResumeDao extends MyBatisDao<UserRankResume> {

}
