package com.sanlux.user.impl.dao;

import com.sanlux.user.model.NotifyArticle;
import io.terminus.common.model.Paging;
import org.junit.Before;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.HashMap;
import java.util.Map;

import static org.assertj.core.util.DateUtil.now;
import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertThat;


/**
 * Code generated by terminus code gen
 * Desc: 公告通知表Dao 测试类
 * Date: 2016-11-07
 */
public class NotifyArticleDaoTest extends BaseDaoTest {



    @Autowired
    private NotifyArticleDao notifyArticleDao;

    private NotifyArticle notifyArticle;

    @Before
    public void init() {
        notifyArticle = make();

        notifyArticleDao.create(notifyArticle);
        assertNotNull(notifyArticle.getId());
    }

    @Test
    public void findById() {
        NotifyArticle notifyArticleExist = notifyArticleDao.findById(notifyArticle.getId());

        assertNotNull(notifyArticleExist);
    }

    @Test
    public void update() {
        // todo
        notifyArticle.setUpdatedAt(now());
        notifyArticleDao.update(notifyArticle);

        NotifyArticle  updated = notifyArticleDao.findById(notifyArticle.getId());
        // todo
        //assertEquals(updated.getHasDisplay(), Boolean.TRUE);
    }

    @Test
    public void delete() {
        notifyArticleDao.delete(notifyArticle.getId());

        NotifyArticle deleted = notifyArticleDao.findById(notifyArticle.getId());
        assertNull(deleted);
    }

    @Test
    public void paging() {
        Map<String, Object> params = new HashMap<>();
        //todo
        //params.put("userId", notifyArticle.getUserId());
        Paging<NotifyArticle > notifyArticlePaging = notifyArticleDao.paging(0, 20, params);

        assertThat(notifyArticlePaging.getTotal(), is(1L));
        assertEquals(notifyArticlePaging.getData().get(0).getId(), notifyArticle.getId());
    }

    private NotifyArticle make() {
        NotifyArticle notifyArticle = new NotifyArticle();

        
        notifyArticle.setTheme("test");
        
        notifyArticle.setContent("content");
        
        notifyArticle.setStatus(1);
        
        notifyArticle.setFileUrl("url");
        
        notifyArticle.setNotifySupplier(1);
        
        notifyArticle.setNotifyDealerFirst(1);
        
        notifyArticle.setNotifyDealerSecond(1);
        
        notifyArticle.setExtraJson(null);
        
        notifyArticle.setCreatedAt(null);
        
        notifyArticle.setUpdatedAt(null);
        

        return notifyArticle;
    }

}